#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/version: "1.15.3"
    version: "1.15.3"
  namespace: gitea
type: Opaque
stringData:
  #@yaml/text-templated-strings
  app.ini: |-

    [cache]
    ADAPTER = memcache
    ENABLED = true
    HOST = gitea-memcached.gitea.svc.cluster.local:11211

    [database]
    DB_TYPE = postgres
    HOST = gitea-postgresql.gitea.svc.cluster.local:5432
    NAME = gitea
    PASSWD = gitea
    USER = gitea

    [metrics]
    ENABLED = false

    [repository]
    ROOT = /data/git/gitea-repositories
    (@- if hasattr(data.values, "extra_repository_config"): @)
    (@= data.values.extra_repository_config -@)
    (@ end @)

    [security]
    INSTALL_LOCK = true

    [server]
    APP_DATA_PATH = /data
    DOMAIN = (@= "gitea.{}".format(data.values.ingress_domain) @)
    ENABLE_PPROF = false
    HTTP_PORT = 3000
    PROTOCOL = http
    ROOT_URL = https://(@-= "gitea.{}".format(data.values.ingress_domain) @)
    SSH_DOMAIN = (@= "gitea.{}".format(data.values.ingress_domain) @)
    SSH_LISTEN_PORT = 22
    SSH_PORT = 22
