#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gitea
  namespace: gitea
spec:
  virtualhost:
    fqdn: #@ "gitea.{}".format(data.values.ingress_domain)
    #@ if(hasattr(data.values, "ingress_secret")):
    tls:
      secretName: #@ data.values.ingress_secret
    #@ end
  routes:
  - services:
    - name: gitea-http
      port: 3000
    conditions:
      - prefix: /