---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: gitea
  namespace: gitea
type: Opaque
data:
  postgresql-postgres-password: "OUVqUThCT3NNQw=="
  postgresql-password: "Z2l0ZWE="
